namespace SystemPulse.Models;

public sealed record SensorSnapshot(
    float? CpuTemperature,
    string CpuTemperatureSource,
    float? CpuLoad,
    float? CpuVoltage,
    float? CpuPowerWatts,
    string CpuElectricalSource,
    float? GpuTemperature,
    float? GpuHotspotTemperature,
    string GpuHotspotTemperatureSource,
    float? GpuLoad,
    float? GpuVoltage,
    float? GpuPowerWatts,
    string GpuElectricalSource,
    float? MemoryTemperature,
    float? MemoryLoad,
    ulong? MemoryUsedBytes,
    ulong? MemoryAvailableBytes,
    ulong? MemoryTotalBytes,
    float? CpuFanRpm,
    string CpuName,
    string GpuName,
    string MemoryName,
    IReadOnlyList<StorageDeviceSnapshot> StorageDevices,
    IReadOnlyList<StoragePerformanceSnapshot> StoragePerformance,
    float? FrameTimeMilliseconds,
    string FrameProcess,
    IReadOnlyList<FrameApplicationSnapshot> FrameApplications,
    float? MotherboardTemperature,
    string MotherboardTemperatureSource,
    DateTime Timestamp,
    bool HasElevatedAccess,
    bool IsPawnIoReady,
    int CpuSensorCount,
    string DriverStatus,
    string? Error = null);

public sealed record StorageDeviceSnapshot(
    string DeviceId,
    string DisplayName,
    ulong? SizeBytes,
    string MediaType,
    string BusType,
    float? Temperature,
    string Health,
    byte? Wear,
    float? TemperatureMaximum = null,
    ulong? PowerOnHours = null,
    ulong? ReadErrorsTotal = null,
    ulong? ReadErrorsUncorrected = null,
    ulong? WriteErrorsTotal = null,
    ulong? WriteErrorsUncorrected = null,
    string SerialNumber = "Not reported",
    string FirmwareVersion = "Not reported",
    string OperationalStatus = "Unknown",
    string PhysicalLocation = "Not reported",
    ulong? UnsafeShutdowns = null,
    string HealthDataSource = "Windows storage provider",
    ulong? VolumeCapacityBytes = null,
    ulong? UsedCapacityBytes = null);

public sealed record StoragePerformanceSnapshot(
    string DeviceId,
    float? Load,
    ulong? ReadBytesPerSecond,
    ulong? WriteBytesPerSecond);

public sealed record FrameApplicationSnapshot(
    int ProcessId,
    string DisplayName,
    float? FrameTimeMilliseconds,
    float? FrameTimeP95Milliseconds = null,
    float? FrameTimeMaximumMilliseconds = null,
    float? FrameTimeDeviationMilliseconds = null,
    float? StutterPercent = null);
